-- Catalog slice 4: the full SRD 5.2 (2024) adventuring-gear table, plus tools,
-- spellcasting focuses, and equipment packs — all under the existing GEAR
-- category so the DM-grant picker and GEAR shops can offer standard kit
-- (Backpack, Crowbar, Torch, Healer's Kit, ...). Until now V25/V30 seeded only
-- the three survival consumables (rations / waterskin / ration-box), so none of
-- the ordinary gear existed in the catalog.
--
-- Prices normalized to copper (1 gp = 100 cp, 1 sp = 10 cp), weights in pounds
-- (0 = negligible), exactly as V11/V12/V25. `bulk` is intentionally left NULL:
-- BulkRules derives the Darker Dungeons rating from the weight bands, which is
-- correct for ordinary objects. `details` is '{}' — plain gear carries no
-- category-specific attributes (V25 convention).
--
-- Sources: rows tagged 'SRD-2024' use SRD 5.2 prices/weights (CC-BY-4.0).
-- Six utility items the 2024 rules dropped from the gear table (hammer,
-- sledgehammer, miner's pick, piton, chalk, soap) are seeded from SRD 5.1
-- and tagged 'SRD-2014' so the provenance stays honest.
--
-- Idempotent: re-running is a no-op on item_key. Deliberately does NOT touch
-- 'rations' / 'waterskin' / 'ration-box' (seeded and re-priced by V25/V30).
INSERT INTO srd_item (item_key, name, category, cost_cp, weight, source, details) VALUES
-- --- Adventuring gear -------------------------------------------------------
('acid',                 'Acid (vial)',                  'GEAR',   2500, 1,    'SRD-2024', '{}'),
('alchemists-fire',      'Alchemist''s Fire (flask)',    'GEAR',   5000, 1,    'SRD-2024', '{}'),
('antitoxin',            'Antitoxin (vial)',             'GEAR',   5000, 0,    'SRD-2024', '{}'),
('arrows-20',            'Arrows (20)',                  'GEAR',    100, 1,    'SRD-2024', '{}'),
('backpack',             'Backpack',                     'GEAR',    200, 5,    'SRD-2024', '{}'),
('ball-bearings',        'Ball Bearings (bag of 1,000)', 'GEAR',    100, 2,    'SRD-2024', '{}'),
('barrel',               'Barrel',                       'GEAR',    200, 70,   'SRD-2024', '{}'),
('basic-poison',         'Basic Poison (vial)',          'GEAR',  10000, 0,    'SRD-2024', '{}'),
('basket',               'Basket',                       'GEAR',     40, 2,    'SRD-2024', '{}'),
('bedroll',              'Bedroll',                      'GEAR',    100, 7,    'SRD-2024', '{}'),
('bell',                 'Bell',                         'GEAR',    100, 0,    'SRD-2024', '{}'),
('blanket',              'Blanket',                      'GEAR',     50, 3,    'SRD-2024', '{}'),
('block-and-tackle',     'Block and Tackle',             'GEAR',    100, 5,    'SRD-2024', '{}'),
('bolts-20',             'Bolts (20)',                   'GEAR',    100, 1.5,  'SRD-2024', '{}'),
('book',                 'Book',                         'GEAR',   2500, 5,    'SRD-2024', '{}'),
('bucket',               'Bucket',                       'GEAR',      5, 2,    'SRD-2024', '{}'),
('caltrops',             'Caltrops (bag of 20)',         'GEAR',    100, 2,    'SRD-2024', '{}'),
('candle',               'Candle',                       'GEAR',      1, 0,    'SRD-2024', '{}'),
('chain',                'Chain (10 feet)',              'GEAR',    500, 10,   'SRD-2024', '{}'),
('chest',                'Chest',                        'GEAR',    500, 25,   'SRD-2024', '{}'),
('climbers-kit',         'Climber''s Kit',               'GEAR',   2500, 12,   'SRD-2024', '{}'),
('costume',              'Costume',                      'GEAR',    500, 4,    'SRD-2024', '{}'),
('crossbow-bolt-case',   'Crossbow Bolt Case',           'GEAR',    100, 1,    'SRD-2024', '{}'),
('crowbar',              'Crowbar',                      'GEAR',    200, 5,    'SRD-2024', '{}'),
('fine-clothes',         'Fine Clothes',                 'GEAR',   1500, 6,    'SRD-2024', '{}'),
('flask',                'Flask',                        'GEAR',      2, 1,    'SRD-2024', '{}'),
('glass-bottle',         'Glass Bottle',                 'GEAR',    200, 2,    'SRD-2024', '{}'),
('grappling-hook',       'Grappling Hook',               'GEAR',    200, 4,    'SRD-2024', '{}'),
('healers-kit',          'Healer''s Kit',                'GEAR',    500, 3,    'SRD-2024', '{}'),
('holy-water',           'Holy Water (flask)',           'GEAR',   2500, 1,    'SRD-2024', '{}'),
('hunting-trap',         'Hunting Trap',                 'GEAR',    500, 25,   'SRD-2024', '{}'),
('ink',                  'Ink (1-ounce bottle)',         'GEAR',   1000, 0,    'SRD-2024', '{}'),
('ink-pen',              'Ink Pen',                      'GEAR',      2, 0,    'SRD-2024', '{}'),
('iron-pot',             'Iron Pot',                     'GEAR',    200, 10,   'SRD-2024', '{}'),
('iron-spikes',          'Iron Spikes (10)',             'GEAR',    100, 5,    'SRD-2024', '{}'),
('jug',                  'Jug',                          'GEAR',      2, 4,    'SRD-2024', '{}'),
('ladder',               'Ladder (10-foot)',             'GEAR',     10, 25,   'SRD-2024', '{}'),
('lamp',                 'Lamp',                         'GEAR',     50, 1,    'SRD-2024', '{}'),
('bullseye-lantern',     'Bullseye Lantern',             'GEAR',   1000, 2,    'SRD-2024', '{}'),
('hooded-lantern',       'Hooded Lantern',               'GEAR',    500, 2,    'SRD-2024', '{}'),
('lock',                 'Lock',                         'GEAR',   1000, 1,    'SRD-2024', '{}'),
('magnifying-glass',     'Magnifying Glass',             'GEAR',  10000, 0,    'SRD-2024', '{}'),
('manacles',             'Manacles',                     'GEAR',    200, 6,    'SRD-2024', '{}'),
('map',                  'Map',                          'GEAR',    100, 0,    'SRD-2024', '{}'),
('map-or-scroll-case',   'Map or Scroll Case',           'GEAR',    100, 1,    'SRD-2024', '{}'),
('mirror',               'Mirror',                       'GEAR',    500, 0.5,  'SRD-2024', '{}'),
('needles-50',           'Needles (50)',                 'GEAR',    100, 1,    'SRD-2024', '{}'),
('oil',                  'Oil (flask)',                  'GEAR',     10, 1,    'SRD-2024', '{}'),
('paper',                'Paper (one sheet)',            'GEAR',     20, 0,    'SRD-2024', '{}'),
('parchment',            'Parchment (one sheet)',        'GEAR',     10, 0,    'SRD-2024', '{}'),
('perfume',              'Perfume (vial)',               'GEAR',    500, 0,    'SRD-2024', '{}'),
('pole',                 'Pole (10-foot)',               'GEAR',      5, 7,    'SRD-2024', '{}'),
('potion-of-healing',    'Potion of Healing',            'GEAR',   5000, 0.5,  'SRD-2024', '{}'),
('pouch',                'Pouch',                        'GEAR',     50, 1,    'SRD-2024', '{}'),
('quiver',               'Quiver',                       'GEAR',    100, 1,    'SRD-2024', '{}'),
('portable-ram',         'Portable Ram',                 'GEAR',    400, 35,   'SRD-2024', '{}'),
('robe',                 'Robe',                         'GEAR',    100, 4,    'SRD-2024', '{}'),
('rope',                 'Rope (50 feet)',               'GEAR',    100, 5,    'SRD-2024', '{}'),
('sack',                 'Sack',                         'GEAR',      1, 0.5,  'SRD-2024', '{}'),
('shovel',               'Shovel',                       'GEAR',    200, 5,    'SRD-2024', '{}'),
('signal-whistle',       'Signal Whistle',               'GEAR',      5, 0,    'SRD-2024', '{}'),
('sling-bullets-20',     'Sling Bullets (20)',           'GEAR',      4, 1.5,  'SRD-2024', '{}'),
('spell-scroll-cantrip', 'Spell Scroll (Cantrip)',       'GEAR',   3000, 0,    'SRD-2024', '{}'),
('spell-scroll-level-1', 'Spell Scroll (Level 1)',       'GEAR',   5000, 0,    'SRD-2024', '{}'),
('spyglass',             'Spyglass',                     'GEAR', 100000, 1,    'SRD-2024', '{}'),
('string',               'String (10 feet)',             'GEAR',     10, 0,    'SRD-2024', '{}'),
('tent',                 'Tent (Two-Person)',            'GEAR',    200, 20,   'SRD-2024', '{}'),
('tinderbox',            'Tinderbox',                    'GEAR',     50, 1,    'SRD-2024', '{}'),
('torch',                'Torch',                        'GEAR',      1, 1,    'SRD-2024', '{}'),
('travelers-clothes',    'Traveler''s Clothes',          'GEAR',    200, 4,    'SRD-2024', '{}'),
('vial',                 'Vial',                         'GEAR',    100, 0,    'SRD-2024', '{}'),
-- --- Spellcasting focuses and the spellbook ---------------------------------
('arcane-focus-crystal',       'Arcane Focus (Crystal)',              'GEAR',  1000, 1, 'SRD-2024', '{}'),
('arcane-focus-orb',           'Arcane Focus (Orb)',                  'GEAR',  2000, 3, 'SRD-2024', '{}'),
('arcane-focus-rod',           'Arcane Focus (Rod)',                  'GEAR',  1000, 2, 'SRD-2024', '{}'),
('arcane-focus-staff',         'Arcane Focus (Staff)',                'GEAR',   500, 4, 'SRD-2024', '{}'),
('arcane-focus-wand',          'Arcane Focus (Wand)',                 'GEAR',  1000, 1, 'SRD-2024', '{}'),
('component-pouch',            'Component Pouch',                     'GEAR',  2500, 2, 'SRD-2024', '{}'),
('druidic-focus-mistletoe',    'Druidic Focus (Sprig of Mistletoe)',  'GEAR',   100, 0, 'SRD-2024', '{}'),
('druidic-focus-wooden-staff', 'Druidic Focus (Wooden Staff)',        'GEAR',   500, 4, 'SRD-2024', '{}'),
('druidic-focus-yew-wand',     'Druidic Focus (Yew Wand)',            'GEAR',  1000, 1, 'SRD-2024', '{}'),
('holy-symbol-amulet',         'Holy Symbol (Amulet)',                'GEAR',   500, 1, 'SRD-2024', '{}'),
('holy-symbol-emblem',         'Holy Symbol (Emblem)',                'GEAR',   500, 0, 'SRD-2024', '{}'),
('holy-symbol-reliquary',      'Holy Symbol (Reliquary)',             'GEAR',   500, 2, 'SRD-2024', '{}'),
('spellbook',                  'Spellbook',                           'GEAR',  5000, 3, 'SRD-2024', '{}'),
-- --- Equipment packs (one line each; contents are in the rules text) --------
('burglars-pack',      'Burglar''s Pack',      'GEAR', 1600, 42, 'SRD-2024', '{}'),
('diplomats-pack',     'Diplomat''s Pack',     'GEAR', 3900, 39, 'SRD-2024', '{}'),
('dungeoneers-pack',   'Dungeoneer''s Pack',   'GEAR', 1200, 55, 'SRD-2024', '{}'),
('entertainers-pack',  'Entertainer''s Pack',  'GEAR', 4000, 58, 'SRD-2024', '{}'),
('explorers-pack',     'Explorer''s Pack',     'GEAR', 1000, 55, 'SRD-2024', '{}'),
('priests-pack',       'Priest''s Pack',       'GEAR', 3300, 29, 'SRD-2024', '{}'),
('scholars-pack',      'Scholar''s Pack',      'GEAR', 4000, 22, 'SRD-2024', '{}'),
-- --- Artisan's tools --------------------------------------------------------
('alchemists-supplies',    'Alchemist''s Supplies',    'GEAR', 5000, 8,  'SRD-2024', '{}'),
('brewers-supplies',       'Brewer''s Supplies',       'GEAR', 2000, 9,  'SRD-2024', '{}'),
('calligraphers-supplies', 'Calligrapher''s Supplies', 'GEAR', 1000, 5,  'SRD-2024', '{}'),
('carpenters-tools',       'Carpenter''s Tools',       'GEAR',  800, 6,  'SRD-2024', '{}'),
('cartographers-tools',    'Cartographer''s Tools',    'GEAR', 1500, 6,  'SRD-2024', '{}'),
('cobblers-tools',         'Cobbler''s Tools',         'GEAR',  500, 5,  'SRD-2024', '{}'),
('cooks-utensils',         'Cook''s Utensils',         'GEAR',  100, 8,  'SRD-2024', '{}'),
('glassblowers-tools',     'Glassblower''s Tools',     'GEAR', 3000, 5,  'SRD-2024', '{}'),
('jewelers-tools',         'Jeweler''s Tools',         'GEAR', 2500, 2,  'SRD-2024', '{}'),
('leatherworkers-tools',   'Leatherworker''s Tools',   'GEAR',  500, 5,  'SRD-2024', '{}'),
('masons-tools',           'Mason''s Tools',           'GEAR', 1000, 8,  'SRD-2024', '{}'),
('painters-supplies',      'Painter''s Supplies',      'GEAR', 1000, 5,  'SRD-2024', '{}'),
('potters-tools',          'Potter''s Tools',          'GEAR', 1000, 3,  'SRD-2024', '{}'),
('smiths-tools',           'Smith''s Tools',           'GEAR', 2000, 8,  'SRD-2024', '{}'),
('tinkers-tools',          'Tinker''s Tools',          'GEAR', 5000, 10, 'SRD-2024', '{}'),
('weavers-tools',          'Weaver''s Tools',          'GEAR',  100, 5,  'SRD-2024', '{}'),
('woodcarvers-tools',      'Woodcarver''s Tools',      'GEAR',  100, 5,  'SRD-2024', '{}'),
-- --- Other tools and kits ---------------------------------------------------
('disguise-kit',      'Disguise Kit',        'GEAR', 2500, 3, 'SRD-2024', '{}'),
('forgery-kit',       'Forgery Kit',         'GEAR', 1500, 5, 'SRD-2024', '{}'),
('herbalism-kit',     'Herbalism Kit',       'GEAR',  500, 3, 'SRD-2024', '{}'),
('navigators-tools',  'Navigator''s Tools',  'GEAR', 2500, 2, 'SRD-2024', '{}'),
('poisoners-kit',     'Poisoner''s Kit',     'GEAR', 5000, 2, 'SRD-2024', '{}'),
('thieves-tools',     'Thieves'' Tools',     'GEAR', 2500, 1, 'SRD-2024', '{}'),
-- --- Gaming sets (2024 lists no weight — negligible) ------------------------
('gaming-set-dice',              'Gaming Set (Dice)',              'GEAR',  10, 0, 'SRD-2024', '{}'),
('gaming-set-dragonchess',       'Gaming Set (Dragonchess)',       'GEAR', 100, 0, 'SRD-2024', '{}'),
('gaming-set-playing-cards',     'Gaming Set (Playing Cards)',     'GEAR',  50, 0, 'SRD-2024', '{}'),
('gaming-set-three-dragon-ante', 'Gaming Set (Three-Dragon Ante)', 'GEAR', 100, 0, 'SRD-2024', '{}'),
-- --- Musical instruments ----------------------------------------------------
('bagpipes',  'Bagpipes',  'GEAR', 3000, 6,  'SRD-2024', '{}'),
('drum',      'Drum',      'GEAR',  600, 3,  'SRD-2024', '{}'),
('dulcimer',  'Dulcimer',  'GEAR', 2500, 10, 'SRD-2024', '{}'),
('flute',     'Flute',     'GEAR',  200, 1,  'SRD-2024', '{}'),
('horn',      'Horn',      'GEAR',  300, 2,  'SRD-2024', '{}'),
('lute',      'Lute',      'GEAR', 3500, 2,  'SRD-2024', '{}'),
('lyre',      'Lyre',      'GEAR', 3000, 2,  'SRD-2024', '{}'),
('pan-flute', 'Pan Flute', 'GEAR', 1200, 2,  'SRD-2024', '{}'),
('shawm',     'Shawm',     'GEAR',  200, 1,  'SRD-2024', '{}'),
('viol',      'Viol',      'GEAR', 3000, 1,  'SRD-2024', '{}'),
-- --- Utility items dropped from the 2024 gear table (SRD 5.1 stats) ---------
('chalk',        'Chalk (1 piece)', 'GEAR', 1,   0,    'SRD-2014', '{}'),
('hammer',       'Hammer',          'GEAR', 100, 3,    'SRD-2014', '{}'),
('sledgehammer', 'Sledgehammer',    'GEAR', 200, 10,   'SRD-2014', '{}'),
('miners-pick',  'Miner''s Pick',   'GEAR', 200, 10,   'SRD-2014', '{}'),
('piton',        'Piton',           'GEAR', 5,   0.25, 'SRD-2014', '{}'),
('soap',         'Soap',            'GEAR', 2,   0,    'SRD-2014', '{}')
ON CONFLICT (item_key) DO NOTHING;
