ALTER TABLE character_manage.pc
    ADD COLUMN IF NOT EXISTS species          TEXT,
    ADD COLUMN IF NOT EXISTS background       TEXT,
    ADD COLUMN IF NOT EXISTS subclass         TEXT,
    ADD COLUMN IF NOT EXISTS alignment        TEXT,
    ADD COLUMN IF NOT EXISTS party            TEXT,
    ADD COLUMN IF NOT EXISTS portrait_tint    TEXT,
    ADD COLUMN IF NOT EXISTS portrait_initials TEXT,
    ADD COLUMN IF NOT EXISTS ability_str      SMALLINT,
    ADD COLUMN IF NOT EXISTS ability_dex      SMALLINT,
    ADD COLUMN IF NOT EXISTS ability_con      SMALLINT,
    ADD COLUMN IF NOT EXISTS ability_int      SMALLINT,
    ADD COLUMN IF NOT EXISTS ability_wis      SMALLINT,
    ADD COLUMN IF NOT EXISTS ability_cha      SMALLINT,
    ADD COLUMN IF NOT EXISTS hp_max           SMALLINT,
    ADD COLUMN IF NOT EXISTS hp_current       SMALLINT,
    ADD COLUMN IF NOT EXISTS hp_temp          SMALLINT,
    ADD COLUMN IF NOT EXISTS ac               SMALLINT,
    ADD COLUMN IF NOT EXISTS initiative       SMALLINT,
    ADD COLUMN IF NOT EXISTS speed            SMALLINT,
    ADD COLUMN IF NOT EXISTS prof_bonus       SMALLINT,
    ADD COLUMN IF NOT EXISTS saves            TEXT,
    ADD COLUMN IF NOT EXISTS skills           TEXT,
    ADD COLUMN IF NOT EXISTS conditions       TEXT,
    ADD COLUMN IF NOT EXISTS coins            TEXT,
    ADD COLUMN IF NOT EXISTS weapons          TEXT,
    ADD COLUMN IF NOT EXISTS gear             TEXT,
    ADD COLUMN IF NOT EXISTS features         TEXT,
    ADD COLUMN IF NOT EXISTS traits           TEXT,
    ADD COLUMN IF NOT EXISTS languages        TEXT,
    ADD COLUMN IF NOT EXISTS tool_profs       TEXT,
    ADD COLUMN IF NOT EXISTS feat             TEXT,
    ADD COLUMN IF NOT EXISTS spell_slots      TEXT,
    ADD COLUMN IF NOT EXISTS bio              TEXT,
    ADD COLUMN IF NOT EXISTS notes            TEXT;

CREATE INDEX IF NOT EXISTS idx_pc_user_id ON character_manage.pc (user_id);
